<?php
/**
 * This file has been automatically generated by yii2-enum, do not change it manually.
 *
 * @date
 */

namespace app\components\enum;

/**
 * Enumeration BoolSimNao
 */
class EnumBoolSimNao extends AbstractEnum
{
    const BOOL_SIM = 1;
    const BOOL_NAO = 0;

    /* @inheritdoc */
    public static $listEnumLabels = [
        self::BOOL_SIM => 'Sim',
        self::BOOL_NAO => 'Não',
    ];
}
