<?php
/**
 * This file has been automatically generated by yii2-enum, do not change it manually.
 *
 * @date
 */

namespace app\components\enum;

/**
 * Enumeration Sexo
 */
class EnumSexo extends AbstractEnum
{
    const SEXO_MASCULINO = 1;
    const SEXO_FEMININO = 2;

    /* @inheritdoc */
    public static $listEnumLabels = [
        self::SEXO_MASCULINO => 'Masculino',
        self::SEXO_FEMININO => 'Feminino',
    ];
}
